from aiogram.fsm.state import StatesGroup, State


class BotStates(StatesGroup):
    checking_auth = State()
    choosing_action = State()
    stock_remains_item = State()
    prediction_item = State()
    asking_prediction = State()
    identifying_period = State()
    remain_choosing_good = State()
    predict_choosing_good = State()
    asking_json = State()
    choosing_predict_period = State()
    asking_editing_fields = State()
    choosing_predict = State()
    no_prediction = State()
    nlp_predict_choosing_good = State()
    admin_choosing_action = State()
    loading_remainings = State()
    loading_turnover = State()
    editing_fields = State()
    authing_again = State()
    choosing_track_action = State()
    track_deleting_item = State()
    adding_track_item = State()
    inserting_track_item = State()
